### ISSUE TITLE
L10N - lost 12 languages in F25 ?

### ISSUE THREAD

**Issue by Jibec** [rhinstaller/anaconda#791]
Hi, please come on translation mailing list and discuss about your new file F25 branch in your Zanata project.
The situation is really bad, we « lost » 12 complete languages from F24 release to F25, we had 21 complete languages before and now only 9.

Here are some stats and the discussion:
https://lists.fedoraproject.org/archives/list/trans@lists.fedoraproject.org/message/IP44UDZN33KLHV3WUPVUSN3TXDEQN2ET/

Here is the weird "main" document in f25 branch, what does it stands for ?
https://fedora.zanata.org/iteration/view/anaconda/f25

thanks a lot for your help!

**Comment by snbueno** [comment]
When I created "f25", I cloned from "master" branch via the Zanata web ui, which is what we customarily do. The list of languages is not maintained by us, however, so I'm not sure I can explain the loss of languages. That was changed with commit 31683dc242c3863c2f36b4331bad474f67d02678 since Zanata manages that information.

As for the "main" documents in Zanata, I'll have to look into that; it is a bit strange to me as well, but I could have missed something.

**Comment by AdamWill** [comment]
@snbueno could this be related to https://github.com/rhinstaller/anaconda/commit/993d8530fdb812a5af09e591163f9524490eb39b and/or https://github.com/rhinstaller/anaconda/commit/0ee1f56d70eda80a5004aa8bc4e730816bd4528b - the commits to drop intltool and autopoint?

**Comment by AdamWill** [comment]
So yeah, I think I'm right. 0ee1f56d70eda80a5004aa8bc4e730816bd4528b completely changed how the `.pot` file that goes to zanata is generated, it's just a totally different system from before. Looking at `po/Makefile.am`, we see this:

    main.pot: $(POTFILE_INPUT)
	    $(GETTEXT_V_EXTRACT)$(XGETTEXT) $(XGETTEXT_OPTIONS) --directory=$(top_srcdir) -o $@ \
	        $(patsubst $(top_srcdir)/%,%,$(POTFILE_INPUT))

    extra.pot: $(POTFILE_EXTRA)
	    $(GETTEXT_V_EXTRACT)$(XGETTEXT) $(XGETTEXT_OPTIONS) -o $@ $(POTFILE_EXTRA)

    $(POTFILE): main.pot extra.pot
	    $(AM_V_GEN)$(MSGCAT) -o $@ --use-first main.pot extra.pot

what that basically means in make-ish is that `$(POTFILE)` - which is going to be `anaconda.pot`, which is really the final pot file which we actually *care* about - is built out of the two intermediate files `main.pot` and `extra.pot`. Those files are kinda just an implementation detail of how we generate `anaconda.pot`; they shouldn't be sent to zanata. I don't know how the 'get the pot files to zanata' step works, but the fix is simply to make sure `main.pot` and `extra.pot` aren't included when that happens.

**Comment by AdamWill** [comment]
I believe https://github.com/rhinstaller/anaconda/pull/820 should fix this, but please check my work, I only just became a Zanata expert in the last five minutes ;)

**Comment by snbueno** [comment]
@AdamWill yeah that explains the existence of the extra pot file. The missing languages however, is not something we can fix on our side though. Thanks for the PR, will look it over later today.

**Comment by AdamWill** [comment]
@snbueno I *think* you're misreading that. I think what @Jibec meant by "we « lost » 12 complete languages from F24 release to F25, we had 21 complete languages before and now only 9." was not "the languages disappeared from zanata" but simply "the languages are no longer complete" - it's just about what the second half of the sentence says, "we had 21 complete languages before and now only 9". It's simply a *consequence* of the extra .pot files showing up. If we nerf the extra .pot files, I would expect the number of complete languages to suddenly jump up again.

**Comment by Jibec** [comment]
+1 Adam, it's what I meant, thank both of you for helping here

**Comment by snbueno** [comment]
@AdamWill ahh, ok, I did misread, so thanks. And we will review the PR soon; thanks for looking into it.

**Comment by AdamWill** [comment]
So after https://github.com/rhinstaller/anaconda/commit/65892659f1d2bacdd2bdfa154af4706963714d54 it looks like master in zanata is back to having a single document:

https://fedora.zanata.org/iteration/view/anaconda/master/documents

but f25 still shows three:

https://fedora.zanata.org/iteration/view/anaconda/f25/documents

If we can fix up the f25 branch before we do the final package builds for F25 release I guess it'd help things...

**Comment by jkonecny12** [comment]
I have cherry-picked the commit and pushed translations so it should be fixed now.
Closing this issue now as fixed.

**Comment by snbueno** [comment]
Thanks, @jkonecny12 , and @AdamWill I'll do a build tomorrow (27-Oct).
