### ISSUE TITLE
Multiple problems: completely unusable UI, misleading info, inconsistent behavior

### ISSUE THREAD

**Issue by wvxvw** [rhinstaller/anaconda#904]
So far I've tried to install Fedora 25 Workstation (default, probably Unity), Fedora 25 Workstation KDE, Fedora 24 Workstation KDE - all have same problems.

1. Anaconda doesn't see available space on SSD. 1 TB SSD has 500 GB of free space, but Anaconda reports 0 free space.
2. Anaconda insists on having `/boot/efi` partition, but EFI is disabled in BIOS, I never asked it to create EFI boot, but even if I play along and tell it to create EFI partition, then, randomly, it will reply with either a message saying "you must create `/boot/efi` partition", or will concede, display a list of changes that it is going to make to the file systems, and upon my pressing "Done", will show me a screen where it will say that "there's a problem with my disk settings".  In either scenario, it is not possible to perform the partitioning I intend.
3. I cannot copy text from the retarded GUI. I cannot even make screenshots, because the way you wrote it, when it displays prompts, all keyboard input is blocked, including `printscreen` key.

This is a total disaster guys... I've been using Fedora since FC 9, and these last couple of releases are a complete let-down. Fedora used to be tested, and reliable... but this is complete garbage.

**Comment by wvxvw** [comment]
The exact same problem exists in Fedora Workstation 24, 23 and 22.  So, it's not a regression, you guys never bothered to test this.

**Comment by celesteking** [comment]
Oh damn, he's like a total clone of me. I too like to piss over developers when I'm angry as hell.

**Comment by celesteking** [comment]
This should be closed as Invalid as guy didn't provide anything useful to start with.

**Comment by snbueno** [comment]
@wvxvw, I will attempt to address your points as best as possible with the information you've provided.

01. That's unfortunate, but without more information (logs), nobody can provide further input.

02. This is another scenario where having logs would be very useful, particularly storage.log.

03. I don't believe it's really possible for something insentient -- in this case, the GUI -- to be retarded. If that was not the intention behind your usage of the word "retarded", hurling invectives is not very useful either since it is not a sufficient description of your problem, nor does it encourage a positive response from the people working on the software. Additionally, you should actually be able to take screenshots. https://docs.fedoraproject.org/en-US/Fedora/25/html-single/Installation_Guide/index.html#sect-installation-screenshots

Regarding your final comment, the installer is tested, fairly extensively, but there is also a lot of ground to cover. There are always unique configurations and situations that unearth new bugs, especially as people adopt new hardware. That's just how software development works. The Fedora QA team works extremely hard, and they're always happy to listen to people such as yourself if you have suggestions for new tests, so I encourage you to reach out to them.

We can continue our discourse if you like, but I'll ask that for issues 01 and 02, you either file separate issues here or on http://bugzilla.redhat.com. Logistically, it's easier for us to have one problem per issue/bug when we plan our work. With those suggestions then, I'm closing this issue and look forward to any additional feedback you have.
