### ISSUE TITLE
 Problems with bond network interface setup

### ISSUE THREAD

**Issue by tkloczko-omni** [rhinstaller/anaconda#91]
I'm trying to setup bond network interface setup over kickstart.

Line from my KS profile with network setup:

network  --bootproto=static --device=bond0 --gateway=172.16.0.222 --hostname=te2.test.net --ip=172.16.0.204 --nameserver=172.16.1.17,172.16.1.18 --netmask=255.255.255.224 --noipv6 --bondslaves=enp2s0f0,enp2s0f1 --bondopts=mode=802.3ad,miimon=100,lacp_rate=fast

After finishing install process in /root/install-post.log i see two errors:

/etc/sysconfig/network-scripts/ifcfg-bond0_slave_1: line 2: slave: command not found
/etc/sysconfig/network-scripts/ifcfg-bond0_slave_2: line 2: slave: command not found

# grep NAME /etc/sysconfig/network-scripts/ifcfg-bond0_slave_{1,2}
/etc/sysconfig/network-scripts/ifcfg-bond0_slave_1:NAME=bond0 slave 1
/etc/sysconfig/network-scripts/ifcfg-bond0_slave_2:NAME=bond0 slave 2

Seems content of the NAME variables is without quotes and this is first bug.

Second one is in /etc/sysconfig/network-scripts/ifcfg-enp2s0f{0,1} files.
Those files are generated with BOOTPROTO=dhcp and should be "BOOTPROTO=none" as long as there is no any other network lines with explicite specified network configuration for slave interfaces.

Above is on Oracle Linux 7 which is using anaconda 19.31.123.

**Comment by sujithpshankar** [comment]
Is there a bugzilla for this?
Bug 1:
I verified that these messages are seen while creating bonding devices using kickstart. (Fedora-22)
However, when kickstart mentions --device="bond0", the NAME values are fully enclosed in quotes and no error is seen. Need info on what is expected here.
Also by quick glance at code, I feel that all virtual devices might encounter this problem. Not yet verified though.
Bug 2:
Need clarity on what is the correct way to create a bonding interface through kickstart. 
Should the slave configurations be specifically mentioned in kickstart during bonding? Otherwise we can see this issue of slaves going to dhcp.

**Comment by bcl** [comment]
Bugs should be handled via normal channels: https://bugzilla.redhat.com

**Comment by tkloczko-omni** [comment]
> Bugs should be handled via normal channels: https://bugzilla.redhat.com

Yes and when I've created one my ticked was closed because I've reported the bug using Oracle Linux.

**Comment by tkloczko-omni** [comment]
> Bug 2:
> Need clarity on what is the correct way to create a bonding interface through kickstart.
> Should the slave configurations be specifically mentioned in kickstart during bonding? Otherwise we can see this issue of slaves going to dhcp.

Slave interfaces needs to be only in Up state. Nothing more.
If someone want to start slave interfaces to add them IPs to send for example probe ICMP packets to check physical path (like it is on some cases on Solaris) this is completely different part of the story and additional network lines with setup of slave interfaces should be added.

IPMP/bonding is working on layer 2 so again all what it necessary is at last one slave interface in Up state.
